config/crd/bases/ols.openshift.io_olsconfigs.yaml

Added CRD for further implementation of the operator
This CRD corresponds to the [application configuration](https://github.com/openshift/lightspeed-service/blob/main/ols/app/models/config.py)
The operator source code will be added later.
- Closes https://issues.redhat.com/browse/OLS-90

OLS-90: Define a configuration CRD to specify OLS configuration

---

Makefile
config/manager/kustomization.yaml

- Update controller image to `quay.io/openshift/lightspeed-operator`.
- The controller image tag is set to the `latest` tag until we figure out how to version the image.
- Closes #

chore: update image repo to openshift organization

---

internal/controller/ols_app_server_assets.go

Bumping up OLS deployment resources as it was failing due to memory issues. Related slack [thread](https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1707501758727439).
Tested in local by bringing up the operator with `make install run` command
Verified that OLS is coming up
```
[vchalla@vchalla-thinkpadp1gen2 ~]$ oc logs pod/lightspeed-app-server-c66b95cc9-tph4l -f
Matplotlib created a temporary cache directory at /tmp/matplotlib-3avg61nb because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2024-02-09 19:32:58,672 [ols.app.main:main.py:29] INFO: Config loaded from …
```

Bumping OLS deployment resources

---

internal/controller/ols_app_server_assets.go

Add `SetControllerReference` [function](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#SetControllerReference) to manage controller resources. 
This is used for garbage collection of the controlled object and for reconciling the owner object.
- Closes #

chore: sets owner as a Controller OwnerReference

---

internal/controller/olsconfig_controller.go

ServiceAccount, Service, and ConfigMap don't have a generation field.
- Closes #

fix: remove unused predicates

---

internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/utils.go

This PR adds the logics to restart app server deployment after an update of `olsconfig` configmap. So that the new config is reloaded by the lightspeed app server. 
It fixes a bug that when operator starts with an existing `olsconfig` configmap, the deployment is updated infinitely because the state cache does not have the configmap's hash. 
Adding the config reload completes the flow described in [OLS-199](https://issues.redhat.com//browse/OLS-199).
- Closes # [OLS-199](https://issues.redhat.com//browse/OLS-199)

OLS-199: restart app server deployment after configmap update

---

.golangci.yaml
Makefile
README.md

Added code linting with the most basic checks.
I deliberately didn't add `golangci-lint` installation via `Makefile`.
Everyone decides how to do this on their workstation, but the PR can be changed if necessary.
Prow's pipeline configuration will be done from another [PR](https://github.com/openshift/release/pull/49054).
- Closes [OLS-341](https://issues.redhat.com/browse/OLS-341)

OLS-341: Add code linter to the OLS operator

---

.gitignore
Makefile
cmd/main.go
config/rbac/role.yaml
go.mod
go.sum
internal/controller/constants.go
internal/controller/ols_console_reconciliator.go
internal/controller/ols_console_reconciliator_test.go
internal/controller/ols_console_ui_assets.go
internal/controller/ols_console_ui_assets_test.go
internal/controller/olsconfig_controller.go
internal/controller/suite_test.go
internal/controller/types.go
internal/controller/utils.go

This PR contain the creation and deletion of the console plugin.
- Closes #[OLS-347](https://issues.redhat.com//browse/OLS-347) [OLS-342](https://issues.redhat.com//browse/OLS-342)

OLS-342, OLS-347: creation and deletion of console plugin

---

Makefile

Unit tests failed with the errors:
```
wget -O .testcrds/openshift-console-crd.yaml https://raw.githubusercontent.com/openshift/api/master/operator/v1/zz_generated.crd-manifests/00_console-operator.crd.yaml
HTTP request sent, awaiting response... 404 Not Found
2024-03-17 02:54:07 ERROR 404: Not Found.
make: *** [.testcrds/openshift-console-crd.yaml] Error 8
```
- Closes #

fix: update Console CRD's URL

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

https://github.com/openshift/lightspeed-service/pull/524 is going to enable tls by default, but the operator isn't ready for TLS to be enabled, so this disables
TLS for now.
- Closes #

OLS-241: Set tls to disabled by default for now

---

internal/controller/constants.go
internal/controller/ols_console_ui_assets.go
internal/controller/ols_console_ui_assets_test.go

This PR completes the[ previous PR on console plugin](https://github.com/openshift/lightspeed-operator/pull/30), by adding a proxy to the OLS application service. 
- Closes #

add proxy from UI to backend service

---

README.md
api/v1alpha1/olsconfig_types.go
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml

The devui was really just a hack until we had a console ui, now that we have one and it's always going to be available when OLS is installed via the operator, there is no reason to enable the devui.
also it definitely shouldn't be something users are exposed to in the CRD
- Closes #

DevUI should always be disabled when OLS is managed by the operator

---

config/rbac/role.yaml
internal/controller/constants.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/olsconfig_controller.go

Added reconciliation of a SAR role and a role binding for the role and the SA.
- Closes # https://issues.redhat.com/browse/OLS-366
```
$ oc get clusterrole/lightspeed-app-server-sar-role -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
creationTimestamp: "2024-03-19T16:44:03Z"
name: lightspeed-app-server-sar-role
ownerReferences:
- apiVersion: ols.openshift.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: OLSConfig
name: cluster
uid: 33271e23-32c4-492e-a85a-5b7f388561dc
resourceVersion: "36448"
uid: 581f4f77-e170-4227-bffe-4a7d8afea45e
rules:
- apiGroups:
- …
```

OLS-366: OLS Service service-account to have SAR create RBAC Role

---

api/v1alpha1/olsconfig_types.go
config/crd/bases/ols.openshift.io_olsconfigs.yaml
internal/controller/constants.go
internal/controller/ols_app_redis_assets.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_console_reconciliator.go
internal/controller/ols_console_ui_assets.go
internal/controller/types.go
internal/controller/utils.go

TLS is enabled for OLS Service .
Provides ability to disable Authorization in CR. 
Example : 
```
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
name: cluster
namespace: openshift-lightspeed
spec:
llm:
providers:
- credentialsSecretRef:
name: openai-api-keys
models:
- name: gpt-3.5-turbo
name: openai
url: https://api.openai.com/v1
ols:
conversationCache:
redis:
maxMemory: 2000mb
maxMemoryPolicy: allkeys-lru
type: redis
defaultModel: gpt-3.5-turbo
defaultProvider: openai
enableDeveloperUI: false
logLevel: INFO
deployment:
replicas: 1
disable_auth: true
```
- Closes #

Enable TLS for OLS Service and add disbale_auth

---

internal/controller/ols_console_ui_assets.go

note: does not enable auth in the OLS backend yet because that is still blocked by OLS-432.
- Closes #

OLS-433: enable user token passing in the consoleplugin config

---

hack/build_catalog.sh

We were leaving the updated files in the system. This change will revert to the original template files after script is completed its run.
- Closes #

 revert files after build_catalog script

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

- Closes #
both endpoints are called periodically
```log
2024-03-27 10:45:46,355 [__main__:runner.py:49] INFO: Config loaded from /etc/ols/..2024_03_27_10_44_49.3941281926/olsconfig.yaml
2024-03-27 10:45:46,355 [ols.src.rag_index.index_loader:index_loader.py:53] WARNING: Embedding model path is not set.
2024-03-27 10:45:46,355 [ols.src.rag_index.index_loader:index_loader.py:54] WARNING: Embedding model is set to default
2024-03-27 10:45:46,355 [ols.src.rag_index.index_loader:index_loader.py:73] WARNING: Index path is not set.
2024-03-27 10:45:46,355 [ols.src.rag_index.index_loader:index_loader.py:91] WARNING: Proceeding without RAG content. Either there is an error or required parameters are not set.
/usr/local/lib/python3.11/site-packages/genai/text/generation/__init__.p …
```

add liveness and readiness probe to application server deployment

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_console_ui_assets.go
internal/controller/utils.go

Make the operator pass the http[s]_proxy, etc environment variables that the OLM sets up for it to the operands: the OLS and the console server.
- Closes # https://issues.redhat.com/browse/OLS-252

OLS-252: Ensure that OLS supports cluster-wide HTTP/HTTPS proxy

---

bundle/manifests/lightspeed-operator-query-access_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/user-access/kustomization.yaml
config/user-access/query_access_clusterrole.yaml

This PR adds a clusterrole to allow non-admin user access OLS API endpoint.
This PR resolves half of the ticket [OLS-444](https://issues.redhat.com/browse/OLS-444). The other half of the ticket is resoved by [PR#75](https://github.com/openshift/lightspeed-operator/pull/75), by granting the service account running OLS app server the permission to create token reviews and subjectaccess reviews. 
- Related Issue # [OLS-444](https://issues.redhat.com//browse/OLS-444)
- Closes #

OLS-444: add a clusterrole to allow user access OLS API endpoint

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/olsconfig_controller.go
internal/controller/utils.go

Fix the issues when the reconcile loop is triggered unnecessarily in multiple cases:
1. The `stateCache` does not contain the `LLMProviderHashStateCacheKey` key.
2. Added sorting of elements for `Volumes/set VolumeMounts` for the correct `Semantic.DeepEqual` comparison
3. Added default volume mode for the correct `Semantic.DeepEqual` comparison
- Closes #
- [] If it is a core feature, I have added thorough tests.

fix: update reconcile logic to avoid repeated reconcile restarts

---

Makefile
README.md
test/e2e/assets.go
test/e2e/client.go
test/e2e/constants.go
test/e2e/http_client.go
test/e2e/reconciliation_test.go
test/e2e/suite_test.go
test/e2e/tls_test.go

End to end tests consist of reconciliation test and the TLS settings verification.
Please have a look on this [PR on liveness and readiness probes](https://github.com/openshift/lightspeed-operator/pull/61), too. The retry of portforwarding in TLS tests can be reduced to a single forward in the test setup if we have the readiness probe.
- Closes # [OLS-227](https://issues.redhat.com//browse/OLS-227)
1. Have a running Openshift cluster.
2. Run the operator `make deploy`
3. Set these 2 environment variables:
- $KUBECONFIG - the path to the config file of kubenetes client
- $LLM_TOKEN - the access token given by the LLM provider, here we use OpenAI for testing.
4. run the e2e test `make test-e2e` 
The output should looks like this 
```shell
➜  lightspeed-operator …
```

OLS-227: add E2E test

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/ols_app_server_assets.go
internal/controller/olsconfig_controller.go

This completes [OLS-444](https://issues.redhat.com//browse/OLS-444), allow the app server service account to create tokenreview, so that it can authenticate users from incoming query.
This PR extracts the authentication activation part of OLS backend from the [PR about service monitor](https://github.com/openshift/lightspeed-operator/pull/75).
- Closes # [OLS-444](https://issues.redhat.com//browse/OLS-444)

OLS-444: allow service account running app server to create tokenreview

---

api/v1alpha1/olsconfig_types.go
config/crd/bases/ols.openshift.io_olsconfigs.yaml

Fix the error
```
Failed to load config file /etc/ols/olsconfig.yaml: default_provider is missing
```
- Closes #

fix: mark defaultProvider as a required field

---

cmd/main.go
internal/controller/ols_console_ui_assets.go
internal/controller/suite_test.go

fix the bug that console UI deployment always use the default image.
- Closes #

fix: console UI image is configurable

---

test/e2e/assets.go
test/e2e/constants.go

A new field `type` is required in the provider spec of OLSConfig CR for validation rules. This PR add this missing field so that the E2E test can execute.
- Closes #

fix: add "type" field to the OLSConfig CR used in E2E tests

---

internal/controller/constants.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/olsconfig_controller.go
internal/controller/resource_watchers.go
internal/controller/resource_watchers_test.go

This PR fix a bug that the LLM token secret referenced by an OLSConfig CR is deleted when the OLSConfig CR is deleted. 
The operator will watch the refertenced secret without owning the secret, reconcile if any changes applied to that LLM token secret. 
This PR replaces https://github.com/openshift/lightspeed-operator/pull/101
This PR makes the operator passes the E2E test. 
- Closes #

fix: OLSConfig CR watches the LLM token secret without owning the secret

---

.gitleaks.toml

follows directions from https://source.redhat.com/departments/it/it-information-security/wiki/pattern_distribution_server to allowlist some dummy secrets that exist in this repo's commit history
- Closes #

Add an allowlist for dummy secrets in the repo

---

Makefile

Increase timeout per test case for the E2E test. Because it takes long time to reconcile the OLS app server deployment.
- Related Issue # [OLS-249](https://issues.redhat.com//browse/OLS-249)
- Closes #

fix: increase timeout per test case to 120m for E2E test.

---

hack/publish_build_from_tag.sh

* Takes arguments for most inputs
* Sets the specified bundle version in the csv(was not being set previously)
* Makes the CSV regexes a bit less fragile(hopefully)
* Removed the ".bak" logic in the sed invocations which didn't seem to serve any purpose because the .bak file was being removed immediately after the sed invocations
* Sets up the restore exit trap only after backup is invoked(there is nothing to restore until backup is invoked)
There's more to do here to collapse the 3 scripts into one (publish, rebuild, update) and create some utility functions, but for now i think this makes it easier to execute a flow like:
1) tag the latest operand images as "candidate"
2) build a new bundle+catalog image from the "candidate" operand images and push the bundle/catalog to your own quay …

Refactor catalog publish script with args

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/olsconfig_controller.go

ServiceAccount that runs the data collection sidecar needs to get the `clusterversions` with name `cluster` . Added Rbac PolicyRules.
- Closes #

Added clusterversions policyrule to get version

---

cmd/main.go
internal/controller/constants.go
internal/controller/olsconfig_controller.go

This PR allows the operator to reconcile even when no event is received. This prevents missing reonciliation and leaves the OLS stack in an inconsistent state.
Rebased https://github.com/openshift/lightspeed-operator/pull/90 . 
Related Issue # [OLS-346](https://issues.redhat.com//browse/OLS-346)
- Closes #

OLS-346: periodic reconciliation

---

test/e2e/autocorrection_test.go
test/e2e/client.go
test/e2e/constants.go
test/e2e/reconciliation_test.go
test/e2e/utils.go

This PR adds E2E tests about reconcile console related resources after unintended modification.
Rebased original PR https://github.com/openshift/lightspeed-operator/pull/89
Added a verification for restoring ConsoleUI configmap. 
Related Issue # [OLS-346](https://issues.redhat.com//browse/OLS-346)
- Closes #

OLS-346: E2e tests for console reconciliaiton

---

README.md
internal/controller/constants.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/ols_console_reconciliator.go
internal/controller/ols_console_reconciliator_test.go
internal/controller/utils.go

This PR add a fix removing logic around CA secrets to  https://github.com/openshift/lightspeed-operator/pull/62
It reconciles for TLS secrets only.
- Closes #

Adding reconcile logic for TLS and CA certs for App & Console

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
cmd/main.go
config/rbac/role.yaml
config/rbac/role_binding.yaml
internal/controller/olsconfig_controller.go
lightspeed-catalog/index.yaml

- Limit Operator access to resources in the namespace `openshift-lightspeed`
- Limit Operator cache to resources in the namespace `openshift-lightspeed`
- Access to cluster resources remains unchanged
- Closes https://issues.redhat.com/browse/OLS-428
- [] If it is a core feature, I have added thorough tests.

OLS-428: reduce Operator scope permissions

---

Dockerfile

Updated operator container image to use UBI image ,rather than distroless image.
- Closes [OLS-640](https://issues.redhat.com/browse/OLS-640)

[OLS-640] Operator Container to use UBI images

---

internal/controller/ols_app_server_deployment.go

Raise the memory limit to 512MB for the data collector container in the deployment `lightspeed-app-server`.
- Closes #

data collector sidecar - raise memory limit to 512MB

---

test/e2e/reconciliation_test.go

This fix is for the version conflict error of updating CR olsconfig during the e2e test. 
for example
```text
Reconciliation From OLSConfig CR [It] should reconcile app configmap after changing application settings
/home/hsun/lightspeed-operator/test/e2e/reconciliation_test.go:130
[FAILED] Unexpected error:
<*errors.StatusError | 0xc00041b220>:
Operation cannot be fulfilled on olsconfigs.ols.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on olsconfigs.ols.openshift.io \"cluster\": the object has been modified; please apply …
```

fix: always update the latest version of CR in e2e reconciliation test

---

Makefile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/olsconfig_controller.go
internal/controller/suite_test.go

Get OLS to retrieve rag content specific to the OCP version the customer is using
- Closes # https://issues.redhat.com/browse/OLS-644

OLS-644: Use version-aligned OCP docs for RAG

---

internal/controller/constants.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/types.go
internal/controller/utils.go

Updated the secret mount path  not to include the filename , so that we can support all secret configurations.
Added azure_openai_config specific confing .
- [] Refactor
- [] New feature
- [ x] Configuration Update
- Related Issue [OLS-620](https://issues.redhat.com/browse/OLS-620)

[OLS-620] Use all fields from provider secret from the user

---

lightspeed-catalog/index.yaml

Complete https://github.com/openshift/lightspeed-operator/pull/140 by cleaning up the remenants of `disableAuth` field in the catalog index.
- Closes #

cleanup: update catalog index to latest CRD

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
cmd/main.go
config/rbac/leader_election_role_binding.yaml
config/rbac/role.yaml
internal/controller/constants.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/olsconfig_controller.go
internal/controller/resource_watchers.go
internal/controller/suite_test.go
internal/controller/utils.go
lightspeed-catalog/index.yaml

disable data collection when telemetry is off. 
Telemetry enablement is determined by the presence of the telemetry pull secret: the presence of the field '.auths."cloud.openshift.com"' indicates that telemetry is enabled.
Use this command to check in an Openshift cluster
```oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' | jq '.auths."cloud.openshift.com"'```
- Related Issue # 
- Closes # OLS-500

OLS-500: disable data collection when telemetry is off

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml

This is the PR to add Konflux pipelines to bundle component, based on[ the PR created  by Konflux bot](https://github.com/openshift/lightspeed-operator/pull/177), adding a upgrade of the image `task-buildah` to fix the bug when building docker images with base image `scratch` (without digest).
- Related Issue # [OLS-768](https://issues.redhat.com//browse/OLS-768)
- Closes #

OLS-768: ci/cd: add Konflux pipelines for the bundle component

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/olsconfig_controller.go
lightspeed-catalog/index.yaml

ServiceAccount used by sidecar only needs to watch the secret (pull-secret) in the namespace (openshift-config) but the controller attempts to watch all secrets in the namespace (openshift-config) . Until we find a long term solution , this PR gives access to all secrets(removed resourcename=pullsecret) 
Same with clusterversions - the controller code attempts to watch it, though we only need to `list and get` the clusterversion (as it will not change). 
- Closes #

Not restricting the secret to pull-secret as a temp fix

---

.tekton/bundle-pull-request.yaml
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/manager/kustomization.yaml

This is step 3 of building our bundle image on konflux. images referenced in the bundle are set to use images built on Konflux.
Attention: Merge the PR on openshift/release before this one, to allow image substitutions on images built on konflux and by consequence the prow CI test will keep working after this PR is merged.
- Related Issue # [OLS-768](https://issues.redhat.com//browse/OLS-768)
- Closes #

OLS-768:  bundle uses konflux built images

---

internal/controller/utils.go
internal/controller/utils_test.go

This PR fixes the issue that when creating the application deployment, the operator immediately reconciles the just created deployment due to a difference in the readiness & liveness probes: the created deployment does not specify all fields and upon next even the comparison between desired deployment and the existing deployment differ in the probe specifications. For example the `FailureThreshold` field.
- Related Issue # [OLS-780](https://issues.redhat.com/browse/OLS-780)
- Closes #

OLS-780: fix double reconciliation on deployment creation

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-pull-request.yaml

fix the syntax for multiple-line string of `pipelinesascode.tekton.dev/on-cel-expression`

fix: multi-line syntax in konflux config

---

internal/controller/constants.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_console_reconciliator.go

wait TLS secret be created before fetching key and certificate when creating application server and the console UI deployment. 
This PR will elimites this error:
```text
2024-06-28T10:07:01+02:00	ERROR	Reconciler	reconcileConsoleUI error	{"task": "reconcile Console Plugin TLS Certs", "error": "secret: lightspeed-console-plugin-cert does not have expected tls.key or tls.crt. error: secret not found: lightspeed-console-plugin-cert. error: Secret \"lightspeed-console-plugin-cert\" not found"}
github.com/openshift/lightspeed-operator/internal/controller.(*OLSConfigReconciler).reconcileConsoleUI
/home/hsun/lightspeed-operator/internal/controller/ols_console_reconciliator.go:52
github.com/openshift/lightspeed-operator/internal/controller.(*OLSConfigReconciler).Reconcile …
```

fix: wait TLS secret be created before fetching key and cert

---

test/e2e/metrics_test.go

This fixes a issue caused by querying multiple timeseries using the `WaitForQueryReturnGreaterEqualOne` function in E2E test
- Closes #

fix: e2e test - metric test aggregaton fix

---

Makefile
hack/update_bundle_catalog.sh

update update_bundle_catalog.sh script to keep relatedImage list in CSV, update default bundle image URL, tags, etc.
- Closes #

OLS-567: update_bundle_catalog.sh preserves relatedImage list in CSV

---

lightspeed-catalog.Dockerfile

Updated the base image with 4.than using latest. We want to  build from SCRATCH , but currently I see a problem with running in 4.15 OCP clusters . We will fix using https://issues.redhat.com/browse/OLS-863
- Closes #

 updated catalog base image with 4.16

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-fbc-pull-request.yaml
.tekton/lightspeed-operator-fbc-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

This replaces https://github.com/openshift/lightspeed-operator/pull/270 by adding the migration of `task-buildah` image.
- Closes #

konflux: migrate task-buildah to 0.2, upgrade on task-prefetch-depenencies

---

Makefile
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15.Dockerfile
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16.Dockerfile
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

The catalog refers production image, the same as bunlde image does.
Add 4.15 and 4.16 version specific dockerfile for catalog images.
The script `update_bundle_catalog.sh` is updated to generate the corret catalog index.
The 2 dockerfile allow us to build FBC component for 4.15 and 4.16 catalog.
The old catalog will be removed afterwards.
Konflux component onboard PRs to merge after this PR:
- ols-fbc-v4-16 https://github.com/openshift/lightspeed-operator/pull/285
- ols-fbc-v4-15 https://github.com/openshift/lightspeed-operator/pull/284
Catalog files are generated by 
```shell
#!/bin/bash
OPERATOR_IMAGE="registry.redhat.io/openshift-lightspeed-beta/lightspeed-rhel9-operator@sha256:049a1a398ed87e4f35c99b36304055c7f75d0188a4d8c1726df59b5f400561e5" …
```

OLS-567: catalog refers production image + version specific dockerfile for catalog

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml

FBC pipeline run only when FBC related file changes. Avoid excessive runs that produce the same FBC image.
Remove deprecated BASE_IMAGES_DIGESTS argument and upgrade buildah task image.
- Closes #

FBC pipeline config update

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml

Updated operator image with images used in snapshot ols-2rx8j, so that we can release that snapshot and all the refered images are present in registry.redhat.io
- [ x] Configuration Update
- Closes #

updated operator image with snapshot ols-2rx8j

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-push.yaml

Added pipelinesascode.tekton.dev/on-cel-expression to the on-push tekton pipelines to be in sync with the on-pull pipelines and to differentiate between the operator and bundle components wrt Konflux notifications.
- Closes #

on-cel-expression for the *push Konflux pipelines

---

lightspeed-catalog-4.15.Dockerfile
lightspeed-catalog-4.16.Dockerfile

The konflux fbc release task `add-fbc-contribution-to-index-image` expects catalogs are kept in subdirectories in OLM's config directory.
- Closes #

OLS-567: add catalog as subdirectory into olm config

---

README.md
hack/snapshot_to_catalog.sh

add a new script `snapshot_to_catalog.sh` to generate catalog index file from Konflux snapshot.
To generate a new catalog index using snapshot `ols-bnxm2` to the catalog file `lightspeed-catalog-4.16/index.yaml` for bundle `0.1.0`, execute this command.
```
./hack/snapshot_to_catalog.sh ols-bnxm2 lightspeed-catalog-4.16/index.yaml
```
- Related Issue # [OLS-855](https://issues.redhat.com//browse/OLS-855)
- Closes #

OLS-885: Catalog generation from konflux snapshot

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

As an OLS admin , I want the ability in the CR to set the context_window_size for my model, so that OLS can send the right content size to the LLM provider.
- Related Issue # https://issues.redhat.com/browse/OLS-810
- Closes #

OLS-810: Create option in olsconfig CRD for context_window_size per model

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml

Removed leftover providers and models (classifier, summarizer, yaml and validator) from the API.
- Closes #

Removed leftover providers and models from the API

---

.tekton/bundle-push.yaml
.tekton/lightspeed-operator-push.yaml

konflux: avoid nudging yaml files in lightspeed-catalog.* directories
- Closes #

konflux: avoid nudging yaml files in lightspeed-catalog.* directories

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml

This completes [the feature PR we merge last week ](https://github.com/openshift/lightspeed-operator/pull/347/files#diff-77ad432f28579f5d0b2d79a9ce7bbc13ac7280d06e3dbd746d790347c5ad465bR502-R517) by adding the new  field OLSDataCollectorSpec into CRD.
- Related Issue # OLS-778, [OLS-514](https://issues.redhat.com//browse/OLS-514)
- Closes #

synchronize bundle with new field OLSDataCollectorSpec in CRD

---

README.md
api/v1alpha1/olsconfig_types.go
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
internal/controller/ols_app_server_assets_test.go

Create RHOAI  and RHELAI config support on the operator side: added rhoai_vllm as a provider type
- Closes # https://issues.redhat.com/browse/OLS-935

OLS-935: Create RHOAI  and RHELAI config support on the operator side

---

hack/snapshot_to_catalog.sh

The script snapshot_to_catalog.sh produce 2 channels `alpha` and `preview` into the catalog.
The channel `preview` has the latest version and skips all older versions.
The channel `alpha` has all versions provided to the script, one replacing the closest older one.
Here is a catalog generated from command `./hack/snapshot_to_catalog.sh -s ols-cq8sl,ols-mdc8x`
More detail see [this PR](https://github.com/openshift/lightspeed-operator/pull/379)
```yaml
---
defaultChannel: preview
icon:
base64data: ...
name: lightspeed-operator
schema: olm.package
---
image: registry.redhat.io/openshift-lightspeed-beta/lightspeed-operator-bundle@sha256:fd3849cb65fee7586b261c8c67336d1d0e5d98e89ae10f87f7ca7945d585b0ff
name: lightspeed-operator.v0.1.3
package: lightspeed-operator
properties:
- type: olm.gvk …
```

OLS-886 snapshot_to_catalog.sh produce 2 channels with multiple bundle versions

---

rhelai_cloud_formation.yaml

AWS CloudFormation template for a RHEL 9.4 EC2 instance ready for installation of RHELAI.
See the top of the file for how to use it.
Notes:
The template expects a ${username}-keys key pair for ssh'ing into the EC2 instance.
The AMI of ami-0aa8fc2422063977a corresponds to RHEL-9.4.0_HVM-20240605-x86_64-82-Hourly2-GP3. This may become out of date.
- Related Issue # https://issues.redhat.com/browse/OLS-986
- Closes #

AWS CloudFormation template for a RHEL 9.4 EC2 instance

---

internal/controller/errors.go
internal/controller/helpers_test.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go

Missing secrets will be pointed out in the status condition "ApiReady" with mentioning the name of secret. 
So that the user can quickly find out the cause.
- Related Issue # 
- Closes # [OLS-881](https://issues.redhat.com//browse/OLS-881)

OLS-881  CRD status points out missing secrets for LLM provider and service TLS certs

---

test/e2e/http_client.go
test/e2e/tls_test.go

Add a test cases that users without the required RBAC roles cannot access the respective OLS API endpoints.
- Closes # [OLS-584](https://issues.redhat.com//browse/OLS-584)

OLS-584: e2e-test - user without RBAC roles are barred off

---

Dockerfile
Makefile
bundle.Dockerfile
hack/update_bundle_catalog.sh
testbundle.Containerfile

use the image registry `registry.redhat.io` to pass the EC check for allowed base image registries.
- Closes #

build: change image registry to registry.redhat.io

---

bundle.Dockerfile
bundle/metadata/annotations.yaml
hack/update_bundle_catalog.sh

The compatiblitiy labels set to `v4.15-v4.17` in bundle.
The tool script `hack/update_bundle_catalog.sh` is updated accordingly, too.
After merging this PR, we go to merge the PR in openshift/release:https://github.com/openshift/release/pull/57108
- Related Issue # [OLS-1073](https://issues.redhat.com//browse/OLS-1073)
- Closes #

OLS-1073: add the supported versions in bundle to 4.15-4.17

---

.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

This PR completes https://github.com/openshift/lightspeed-operator/pull/442
add on-cel-expression filters to avoid excessive build on unrelated files.
- Related Issue # [OLS-1074](https://issues.redhat.com//browse/OLS-1074)
- Closes #

OLS-1074: konflux - udpate fbc-4.17 pipelines

---

bundle/manifests/lightspeed-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
config/prometheus/monitor-operator.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

Fix the bug that PrometheusOperatorRejectedResources alert is trigger if the namespace openshift-lightspeed does not have the label `openshift.io/cluster-monitoring: true` . 
We add the label `openshift.io/user-monitoring: false` to ServiceMonitor so that the prometheus operator of User Workload Monitoring stack will not process these ServiceMonitors.
- Related Issue # [OLS-1009](https://issues.redhat.com//browse/OLS-1009)
- Closes #

OLS-1009 bugfix: add label `openshift.io/user-monitoring: false` to ServiceMonitors

---

test/e2e/autocorrection_test.go

This fix will eliminate this kind of false failure that the console deployment is not created in time: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-operator/453/pull-ci-openshift-lightspeed-operator-main-bundle-e2e-4-17/1841826432234295296
- Closes #

e2e test: add wait in console resore tests, reduce false failure

---

.tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml

OLS-1058 - Adding OLS e2e tests

---

.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Restore Konflux pipeline settings after upgrade in https://github.com/openshift/lightspeed-operator/pull/482.
- Related Issue # https://issues.redhat.com/browse/OLS-1083
- Closes #

Restore Konflux pipeline settings after upgrade

---

.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml

[OLS-1151](https://issues.redhat.com//browse/OLS-1151): Remove enterprise contract warnings from Konflux pipelines - fbc-v4-16
- Related Issue # https://issues.redhat.com/browse/OLS-1151
- Closes #

OLS-1151: Remove enterprise contract warnings from Konflux pipelines - fbc-v4-16

---

cmd/main.go
internal/tls/tls_security_profile.go

This PR is baded on https://github.com/openshift/lightspeed-operator/pull/481 , if we merge this PR, we can close the PR#481
When operator starts, it tries to fetch TLS Security Profile from the OLSConfig CR or the APIServer CR. 
If neither of these 2 CRs defines TLS Security Profile, the default "Intermediate" level TLS Security Profile will be used.
The operator is based on controller-runtime that is not capable of restarting the metrics server on running. The user should manually restart the operator pod if it wants to enforce the new TLS Security Profile.
- Related Issue # [OLS-1097](https://issues.redhat.com//browse/OLS-1097)
- Closes # [OLS-1098](https://issues.redhat.com//browse/OLS-1098)
- How were the …

OLS-1098: Metric Server Enforce TLS Security Profile

---

renovate.json

Renovate bot does not update image references in catalogs. Because these updates are not consistent with the bundle content and we need to control catalog updates for each release. We do not want Renovate bot interfere with our releasing procedure.
- Related Issue # [OLS-1161](https://issues.redhat.com//browse/OLS-1161)
- Closes #

OLS-1161: konflux: renovate bot does not update image references in catalogs

---

Dockerfile

use rhel-9-4-els/rhel instead of ubi-minimal base image
- Closes # [OLS-1181](https://issues.redhat.com//browse/OLS-1181)

OLS-1181:  FIPS compliance - use rhel-9-4-els/rhel as base image

---

bundle.Dockerfile

use rhel-9-4-els/rhel instead of ubi-minimal base image in bundle
- Closes # [OLS-1193](https://issues.redhat.com//browse/OLS-1193)

OLS-1193: FIPS compliance - use rhel-9-4-els/rhel in bundle image

---

Dockerfile
bundle.Dockerfile

Switch back to UBI9 image as base image. The new UBI9 images are already FIPS-140-3 compliant.
- Related Issue # [OLS-1244](https://issues.redhat.com/browse/OLS-1244)  [OLS-1181](https://issues.redhat.com/browse/OLS-1181)
- Closes #

config: base image switch back to ubi9 minimal, FIPS compliant version.

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
bundle.Dockerfile

[OLS-1256](https://issues.redhat.com//browse/OLS-1256): Add OLS ARM builds to Konflux - bundle
- Related Issue # https://issues.redhat.com/browse/OLS-1256
- Closes #

OLS-1256: Add OLS ARM builds to Konflux - bundle

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

Fix the EC violations on FBC components
```text
[Violation] hermetic_build_task.build_task_hermetic
ImageRef: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols-fbc-v4-17/fbc-v4-17@sha256:5a97493c08277f1e5374ed87ef4f937734b7feb1045a3ee237c30b06500e8bf0
Reason: Build task was not invoked with the hermetic parameter set
Title: Build task called with hermetic param set
Description: Verify the build task in the PipelineRun attestation was invoked with the proper parameters to make the build
process hermetic. To exclude this rule add "hermetic_build_task.build_task_hermetic" to the `exclude` section of the policy
configuration.
Solution: Make sure the task that builds the image has a parameter named 'HERMETIC' and it's set to 'true'.
✕ [Violation] tasks.pinned_task_refs
ImageRef: …
```

config: enable hermetic build for FBC + pin task "task-validate-fbc"

---

.tekton/fbc-v4-15-push.yaml

fix the bug that fbc-4.15 is not run when we update the pipeline config file `.tekton/fbc-v4-15-push.yaml`
- Closes #

config: fbc-4.15 cel expression update"

---

renovate.json

fix the ignorePaths in renovate bot configuration. 
Renovate was still trying to update the catalog indexes after the intial renovate config is in place, for example: 
https://github.com/openshift/lightspeed-operator/pull/550
- Closes #

config: fix ignorePaths in renovate config

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
bundle/metadata/annotations.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/rbac/role.yaml
hack/update_bundle.sh

add FIPS-compliant annotation in bundle.
This PR is based on https://github.com/openshift/lightspeed-operator/pull/572 that regenerate bundle manifests using controller-tools 0.16. If we merge this PR, we can close the PR #572 
- Closes # [OLS-1270](https://issues.redhat.com//browse/OLS-1270)

OLS-1270: add FIPS-compliant annotation in bundle

---

test/e2e/metrics_test.go
test/e2e/prometheus_client.go

increase prometheus query timeout to 95s so that it has time for 3 scrapes, making metrics test less flaky.
- Related Issue # [OLS-1333](https://issues.redhat.com//browse/OLS-1333)
- Closes #

OLS-1333 test: increase prometheus query timeout to 95s

---

test/e2e/autocorrection_test.go

This fixes the problem when updating resources for testing the reconciliation, test behave flakiness with version conflict errors during updates.
- Related Issue # [OLS-1333](https://issues.redhat.com//browse/OLS-1333)
- Closes #

OLS-1333 test: reduce version conflicts when updating resources

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

For the new component in ols-bundle named `ols-bundle` , we want the same config as the `bundle` image that we build in `ols` konflux application. This PR gets the config from the ols application's bundle component to ols-bundle application's ols-bundle.
- Closes #

 sync the ols-bundle with original ols

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

Update the Konflux task-buildah-remote-oci-ta task to the latest version to work around the "Mismatched SBOM formats: cyclonedx X spdx" build-image error.
- [] Configuration Update
- Closes #

Update the Konflux task-buildah-remote-oci-ta task to the latest version

---

hack/release_tools.md
hack/snapshot_to_catalog.sh
hack/snapshot_to_image_list.sh

We have 2 applications in konflux from which the image list has to be computed to generate catalog updates . Updated our toos to take ols-bundle snapshot as a argument to get the image and use that for image identification.
- Closes #

update image list to computed from ols and ols-bundle

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

add new field `introspectionEnabled` to OLSConfig CRD. 
- Closes # [OLS-1392](https://issues.redhat.com//browse/OLS-1392)

OLS-1392: add option introspectionEnabled

---

internal/controller/errors.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/olsconfig_controller.go

Missing `apitoken` key in the LLM provider secret will not trigger app server reconciliation, avoid crashlooping of the app pod.
OLSConfig CR status field will have the error message when this issue happens.
- Closes # [OLS-1449](https://issues.redhat.com//browse/OLS-1449)

OLS-1449: bugfix: gracefully handle missing apitoken key in the LLM provider secret

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
lightspeed-catalog-4.17/index.yaml

Corrected the list of LLMs in the operator description so that the operator details page renders the LLMs as an unnumbered list.
Before:
OpenAI Microsoft Azure OpenAI IBM WatsonX
After:
- OpenAI
- Microsoft Azure OpenAI
- IBM WatsonX
- Closes #

Fix the LLM list markdown in the operator description

---

related_images.json

OLS release 0.3.4 - create bundle using snapshot ols-q445n
name: ols-q445n
components:
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-console@sha256:66ccebc81857f966df2189f24c89c2d826dc323718e8c0fab8f98c963bb0fead
name: lightspeed-console
source:
git:
revision: 61b4d4e4acf2dc5859c94f943982660093693dec
url: https://github.com/openshift/lightspeed-console
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-operator@sha256:c3a2009a40de6f4a7c89db209b26b669afffdf654ec4654e31d4d4cdc4067938
name: lightspeed-operator
source:
git:
dockerfileUrl: Dockerfile
revision: a759f7689ae604b2ec1730be93bd571689a01fb5
url: https://github.com/openshift/lightspeed-operator
- containerImage: …

create bundle using snapshot ols-q445n

---

test/e2e/client.go
test/e2e/metrics_test.go
test/e2e/prometheus_client.go

- increase prometheus client timeout to 120 sec
- retry whole metrics_test in case of test failure (use Ginkgo's FlakyAttempts construction)
- fix issue with ClusterRoleBindings on clusterbot ROSA clusters - not able to delete (ignore error if ClusterRoleBindings already exist)
- retry on getting prometheus route in case of networking issue

OLS-1333: Fix prometheus metrics test flakyness

---

test/e2e/client.go
test/e2e/tls_test.go

[OLS-1333](https://issues.redhat.com//browse/OLS-1333): Fix e2e tls_test test flakyness
- retry whole tls_test in case of test failure (use Ginkgo's FlakyAttempts construction)
- fix issue with ServiceAccount on clusterbot ROSA clusters - not able to delete (ignore error if service account already exist)
- minor fixes when the cleanup functions are executed

OLS-1333: Fix e2e tls_test test flakyness

---

test/e2e/utils.go

Fix for mainline break in test/unit
```
go vet ./...
...
test/e2e/utils.go:24:7: the cancel function returned by context.WithCancel should be called, not discarded, to avoid a context leak
test/e2e/utils.go:41:7: the cancel function returned by context.WithCancel should be called, not discarded, to avoid a context leak
```
- Closes #

Fix for 'go vet' breakage: the cancel function returned by context.WithCancel should be called

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Generate the following
```
mcp_servers:
- name: openshift
transport: stdio
stdio:
command: python
args: 
- ./mcp_local/openshift.py 
```
into the OLS service configuration if the `OLSConfig.spec.ols.introspectionEnabled` flag is set in the CR.
- Closes # https://issues.redhat.com/browse/OLS-1711

OLS-1711: [Operator] Set default MCP config when Introspection is enabled

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manager/manager.yaml
internal/controller/ols_app_postgres_assets.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_console_ui_assets.go

This reverts commit 32e8649bb26a85060e2c1c5b2864dd878e1a2c84 "added readOnlyRootFilesystem for containers"
- Closes #

Revert "added readOnlyRootFilesystem for containers"

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manager/manager.yaml
internal/controller/constants.go
internal/controller/ols_app_postgres_assets.go
internal/controller/ols_app_postgres_assets_test.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_console_ui_assets.go

This PR brings back the original commit (https://github.com/openshift/lightspeed-operator/pull/736) with the r/o root fs (thus undoing https://github.com/openshift/lightspeed-operator/pull/744), and adds writable volumes to the operand Deployments where needed.
It weakly depends on https://github.com/openshift/lightspeed-console/pull/759.
- Closes # https://issues.redhat.com/browse/OLS-1552

OLS-1770: Add writable volumes to the operand Deployments to compensate for read-only root fs

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

Konflux enforce new enterprise policy that multi-arch index is not allowed for bundle images. we are disabling the image index build as instructed in : https://groups.google.com/u/1/a/redhat.com/g/konflux-announce/c/nfJ58NkZXTE
- Closes #

OLS-1734: conf: disable building image index for bundle as

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

- Related Issue # [OLS-1734](https://issues.redhat.com//browse/OLS-1734)
- Closes #

OLS-1734 fix: call python3.11 to start MCP servers

---

Dockerfile

update golang to 1.23
deblocks the dependency upgrades that waiting to merge for months.
- Closes # [OLS-1699](https://issues.redhat.com//browse/OLS-1699)

OLS-1699 conf: update base image to gotoolset-1.23

---

Makefile

to fix the problem encountered in https://github.com/openshift/release/pull/65373 : 
error log for `make generate` https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/65373/rehearse-65373-pull-ci-openshift-lightspeed-operator-main-generate/1927299720154189824
- Closes #

OLS-1699 bugfix: avoid CI use vendor mode to install go tools

---

lightspeed-catalog-4.19/index.yaml

Add OCP 4.19 operator catalog indexfile .
Generated using command :
` ./hack/snapshot_to_catalog.sh -s ols-vd4zh -b ols-bundle-z8tgw -c lightspeed-catalog-4.19/index.yaml -n alpha,stable -m`
- [ x] New feature
- Closes #

Add OCP 4.19 operator catalog indexfile

---

bundle/manifests/lightspeed-operator-metrics-reader-token_v1_secret.yaml
bundle/manifests/lightspeed-operator-metrics-reader_v1_serviceaccount.yaml
bundle/manifests/lightspeed-operator-ols-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/lightspeed-operator-prometheus-operator_rbac.authorization.k8s.io_v1_role.yaml
bundle/manifests/lightspeed-operator-prometheus-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
config/prometheus/clusterrole_binding.yaml
config/prometheus/kustomization.yaml
config/prometheus/role.yaml
config/prometheus/role_binding.yaml
config/prometheus/secret-sa-token.yaml
config/prometheus/service-account.yaml
internal/controller/constants.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/operator_reconciliator.go
internal/controller/operator_reconciliator_test.go

Replace BearerTokenSecret with Authorization field in ServiceMonitor.
A new service account is created to access metrics endpoints. All priveledges on service account `prometheus-k8s` is removed, only need pass the token to the SA `prometheus-operator`
- Closes # [OLS-1322](https://issues.redhat.com//browse/OLS-1322)

OLS-1322 - bugfix: Replace BearerTokenSecret with Authorization field in ServiceMonitor

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/rag.go
internal/controller/rag_test.go

For BYOK images with floating tags, such as `latest`, the OLS can not reload even after a restart because of the hardcoded ImagePullPolicy of PullIfNotPresent. Changing the ImagePullPolicy to PullAlways resolved this issue. Now the BYOK images will always be pulled from the container registry every time OLS starts.
- Closes # https://issues.redhat.com/browse/OLS-1956

OLS-1956: Change the ImagePullPolicy for BYOK images to PullAlways

---

test/e2e/byok_test.go

Added an e2e test to verify that specifying only the image is now sufficient for BYOK images.
- Related Issue # https://issues.redhat.com/browse/OLS-1915
- Closes #

OLS-1915: added a BYOK e2e test

---

.gitignore
Makefile
test/e2e/client.go
test/e2e/database_test.go

Add test case for database persistency. It requires the testing cluster have storage class `gp3-csi`.
Add a new makefile entry to run e2e tests without this database persistency test case, as it uses `local` storage class and it is flaky in cluster with more than 1 worker nodes.
- Closes # [OLS-1848](https://issues.redhat.com//browse/OLS-1848)

OLS-1848: test database persistency

---

Makefile

some yq version cannot create the directory
- Closes #

fix: make the directory release-konflux/ when creating release objects

---

hack/release-konflux/kustomization.yaml

take note of the snapshots used in the release 1.0.3

tool: update konflux snapshots for 1.0.3 in release objects

---

Makefile

fix the yq download URL and missing PATH problem when using `make bundle` . 
- Closes #

tools: fix yq jq path in bundle building

---

hack/snapshot_to_image_list.sh
related_images.json

Updated related_images.json for OLS 1.0.4
Fixed hack/snapshot_to_image_list.sh to handle the MCP server image correctly - Konflux seems to have changed the image naming scheme where the application name is not used anymore.
- Related Issue # https://issues.redhat.com/browse/OLS-2024
- Closes # 

Update related_images.json for OLS 1.0.4

---

cmd/main.go
internal/controller/constants.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/olsconfig_controller.go

Use openshift-mcp-server consistently in the operator sources. The bundle changes are in https://github.com/openshift/lightspeed-operator/pull/943.
- Related Issue # https://issues.redhat.com/browse/OLS-2024
- Closes #

OLS-2024: OLS 1.0.4. Consistent use of openshift-mcp-server, operator changes

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

In the generated olsconfig config map, MCP server config should have either the `sse` field or the `streamable_http` field, not both. 
- Closes # [OLS-2071](https://issues.redhat.com//browse/OLS-2071)

fix: MCP config should export settings for one transport only

---

Dockerfile

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for lightspeed-operator
