openshift/lightspeed-operator

OWNERS

Update OWNERS adding vbelouso and raptorsun

---

internal/controller/olsconfig_controller.go

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
trigger Prow test pipeline
- [] Bug fix
- Closes #

chore: trigger Prow test pipeline

---

README.md

Updated doc with default values for openai provider.
- Closes #

 updated readme to match api swagger

---

internal/controller/ols_app_server_reconciliator.go

No update on configmap if the config file `olsconfig.yaml`  content does not change. 
- Closes #

Update configmap only if the olsconfig.yaml content changes

---

internal/controller/constants.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_reconciliator_test.go

- Closes # [OLS-255](https://issues.redhat.com//browse/OLS-255)

OLS-225:  add unit tests

---

internal/controller/ols_app_server_reconciliator.go

Add a return to exit from the function after creating resources.
- Closes #

fix: add early return for the created resources

---

internal/controller/constants.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_deployment.go
internal/controller/olsconfig_controller.go

Fix errors found by the linter
- Closes #

chore: fix linter issues

---

README.md

Update conversation cache settings to use only Redis
- Closes #

docs: update info for the Operator local installation

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

Add emptyDir volume to ols deployment

OLS-397: Add emptyDir volume to ols deployment

---

README.md
api/v1alpha1/olsconfig_types.go
cmd/main.go
config/crd/bases/ols.openshift.io_olsconfigs.yaml
internal/controller/constants.go
internal/controller/ols_app_redis_assets.go
internal/controller/ols_app_redis_assets_test.go
internal/controller/ols_app_redis_reconciliator.go
internal/controller/ols_app_redis_reconciliator_test.go
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_app_server_reconciliator.go
internal/controller/ols_app_server_reconciliator_test.go
internal/controller/ols_console_reconciliator.go
internal/controller/ols_console_reconciliator_test.go
internal/controller/ols_console_ui_assets.go
internal/controller/ols_console_ui_assets_test.go
internal/controller/olsconfig_controller.go
internal/controller/suite_test.go

Chagne the OLSConfig CRD to a cluster scoped CRD.
- Closes #

OLS-367: change OLSConfig CRD to cluster scope.

---

internal/controller/ols_app_server_assets.go

this change is a no-op since both constants have the same value, but avoids a potential future issue if one of them is changed.
- Closes #

Use the service name constant for the service name

---

config/rbac/role.yaml
internal/controller/olsconfig_controller.go

Adding access for managing secrets.

Adding access for secrets

---

config/rbac/role.yaml
internal/controller/olsconfig_controller.go

updated manager-role for access to secrets

---

hack/build_catalog.sh

fix opm path

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml

Remove incorrect image.
- Closes #

fix incorrect image

---

.github/dependabot.yml

Update Dependabot to check new package versions weekly.
- Closes #

chore: run Dependabot weekly

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

OLS-441: add hardcoded rag reference configuration

---

.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Enable build of source image in Konflux
- Related Issue # https://issues.redhat.com/browse/OLS-389
- Closes #

Konflux: build source image

---

internal/controller/ols_console_reconciliator.go

Fixed typos - PR to kick off a build.
- Closes #

fixed typos in log message

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Add Uvicorn log level settings according to https://github.com/openshift/lightspeed-service/pull/674
- [] Configuration Update
- Closes #

chore: add Uvicorn log level

---

api/v1alpha1/olsconfig_types.go
config/crd/bases/ols.openshift.io_olsconfigs.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
Added support for IBM Watsonx and Azure OpenAI
- Closes https://issues.redhat.com/browse/OLS-308

OLS-308: Add watsonx and Azure OpenAI support

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
config/samples/ols_v1alpha1_olsconfig.yaml
internal/controller/ols_app_server_assets_test.go

Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
Added CSV markers to improve the user experience in the OpenShift UI and data validation
- Closes https://issues.redhat.com/browse/OLS-510

OLS-510: Add CSV code markers to the CRD

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Add a user data collection config entry.

Enable collection

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

Add user data collector sidecar to deployment.

OLS-498: Add user data collector sidecar to deployment

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

Added PolicyRule to get for pull-secret present in namespace openshift-config
- Closes #

 add PolicyRule to get for pull-secret

---

hack/publish_package_builds.sh

csv changes using this script:
```
containers:
- args:
- --health-probe-bind-address=:8081
- --metrics-bind-address=127.0.0.1:8080
- --leader-elect
- --images=lightspeed-service=quay.io/openshift/lightspeed-service-api@sha256:46ef4024920f42504cd46c2e61d22946640fb996f9e2cfcf10e10e453a217802,console-plugin=quay.io/openshift/lightspeed-console-plugin@sha256:41c62c778a20e929a014300012916ec738950b035ee7c65706e9b53b5c79ce40
```
```
image: quay.io/openshift/lightspeed-operator@sha256:20919c49eb1668783b288d71a31c98a3d5cb61aef0bddf2495a9d2586f891393
```
Catalog index.yaml changes:
```
relatedImages:
- image: quay.io/bparees/lightspeed-operator-bundle@sha256:4716f552bcfd82d5960cb07bf9d50890934fb0fdd75aa29bdceb72a1fa7d984c
name: ""
- image: …
```

use SHAs when publishing bundle/catalog

---

lightspeed-catalog/index.yaml

Updating the catalog index file. It appears I missed to push in my last commit.
- Closes #

Chore: updated catalog index file

---

Makefile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
cmd/main.go
config/default/kustomization.yaml
config/manager/kustomization.yaml
hack/example_catalogsource.yaml
hack/publish_package_builds.sh
hack/update_bundle_catalog.sh
internal/controller/constants.go
lightspeed-catalog/index.yaml

Updated container image reference from Org openshift to openshift-lightspeed
- Closes #

moving to quay Org openshift-lightspeed

---

test/e2e/client.go
test/e2e/reconciliation_test.go

This PR skips wait for deployment rollout when checking spec modifications.
It saves about 150 seconds per run. 
- Related Issue # [OLS-576](https://issues.redhat.com//browse/OLS-576)
- Closes #

OLS-576: Accelerate E2E test

---

.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Enabled hermetic builds based on 
(1)  https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_hermetic-builds/ 
(2) https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_prefetching-dependencies-to-support-hermetic-build/
- Closes #

[OLS-391] Enable hermetic build on konflux

---

.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Enabled default source Image in tekton config.
- Related Issue [#](https://issues.redhat.com/browse/OLS-391)
- Closes #

[OLS-391] enabled default build source image

---

test/e2e/client.go
test/e2e/tls_test.go

We use a normal service account instead of the cluster admin to test access to the API endpoints and metrics endpoints.
- Closes #

use normal service account to test API endpoint access

---

internal/controller/ols_app_server_deployment.go

Lower collector container resources

OLS-694: Lower collector container resources

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
lightspeed-catalog/index.yaml

Adding fake_provider as one of supported provider, which will be helpful for load testing.
- Closes # https://issues.redhat.com/browse/OLS-687?filter=-1 
- 
Tested and verified in local and CI tests went through.

Add support for fake llm provider in operator as well

---

.snyk

This PR adds Snyk config to ignore test codes in security check.
It works after we merged this PR in openshift/release to set the path to Snyk config file: https://github.com/openshift/release/pull/53381
- Closes #

add Snyk config to ignore test codes in security check

---

Dockerfile

Copy license file into container
It will make Konflux linter happy

Copy license file into container

---

.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

The hermetic build has been removed with previous updates . Enabling again . 
- Closes #

reenable hermetic builds 

---

README.md

Adding an explanation about the compatible LLMs.
- Closes #

Update README.md to include information about other LLMs

---

konflux-integration/pipeline.yaml

Stub for Tekton pipeline for integration tests
- Related Issue #[OLS-703](https://issues.redhat.com//browse/OLS-703)

OLS-703: Stub for Tekton pipeline for integration tests

---

konflux-integration/pipeline.yaml

Konflux integration tests: Info about images to be tested
- Related Issue #[OLS-702](https://issues.redhat.com//browse/OLS-702)

OLS-702: Konflux integration tests: Info about images to be tested

---

test/e2e/autocorrection_test.go
test/e2e/utils.go

Make int32Ptr generic
- Closes #

Make int32Ptr generic

---

README.md

OLS-716: Update lightspeed operator readme file

---

.tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml
.tekton/integration-tests/tasks/ols-e2e.yaml
.tekton/integration-tests/tasks/ols-installer.yaml

Creating a pipeline for the provisioning and deprovisioning of ROSA clusters and running an 'installer' and 'test' tasks
- Closes #

Konflux integration tests

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go
internal/controller/ols_console_ui_assets.go
internal/controller/ols_console_ui_assets_test.go

This PR removes the CPU limit of all containers, unleash them for better performance.
- Related Issue # [OLS-790](https://issues.redhat.com//browse/OLS-790)
- Closes # [OLS-790](https://issues.redhat.com//browse/OLS-790)

OLS-790: remove cpu limit for all containers

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

increase CPU request to 500m for app server container

---

.tekton/lightspeed-operator-pull-request.yaml

This PR avoid building operator for changes in unrelated files such as those inside the `bundle` directory.
- Closes #

build: konflux does not build operator on unrelated changes

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

Resolving issues from "enterprise contract" validations.
Progress: 
1. bundle image labels
2. CSV labels
3. SBOM files
4. 
- Related Issue # [OLS-822](https://issues.redhat.com//browse/OLS-822)
- Closes # 

fix: enterprise contract 

---

.tekton/bundle-pull-request.yaml
.tekton/lightspeed-operator-pull-request.yaml

… update
1. fix tekton config file typo
2. trigger pipeline run on pipeline config update
- Closes #

konflux config fix

---

.tekton/lightspeed-operator-pull-request.yaml

fix the triggering condition in pull request for the operator konflux pipeline run.

fix cel expression for operator pull request pipeline

---

bundle.Dockerfile

fix EC issue, that last one preflight check.
- Related Issue # [OLS-822](https://issues.redhat.com//browse/OLS-822)
- Closes #

fix: e2e test - konflux preflight-check - bundle dockerfile conformity

---

.tekton/lightspeed-operator-fbc-pull-request.yaml
.tekton/lightspeed-operator-fbc-push.yaml

to avoid uneccessary build of catalog images.
- Closes #

OLS-567: konflux build FBC only when catalog related files change

---

hack/update_bundle_catalog.sh

fix a syntax error bug when using `RELATED_IMAGE` variable when calling `update_bundle_catalog.sh`
- Closes #

OLS-567: fix syntax error in update_bundle_catalog.sh

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/manager/imagedigestmirrorset.yaml
config/manager/kustomization.yaml
hack/update_bundle_catalog.sh

Make bunlde refer to images from production repository.
For CI prow tests, we use image substitutions defined in this PR https://github.com/openshift/release/pull/54620
For konflux tests, we are going to create ImageDigestMirrorSet to point images to images built in PR.
Content is generated by these commands
```shell
#!/bin/bash
OPERATOR_IMAGE="registry.redhat.io/openshift-lightspeed-beta/lightspeed-rhel9-operator:0.0.1"
BUNDLE_IMAGE="registry.redhat.io/openshift-lightspeed-beta/lightspeed-operator-bundle:0.0.1"
CONSOLE_IMAGE="registry.redhat.io/openshift-lightspeed-beta/lightspeed-console-plugin-rhel9:0.0.1"
SERVICE_IMAGE="registry.redhat.io/openshift-lightspeed-beta/lightspeed-service-api-rhel9:0.0.1"
RELATED_IMAGES=$(
cat <<-EOF
[
{
"name": "lightspeed-service-api",
"image": …
```

OLS-567: Bunlde uses production images

---

bundle.Dockerfile
hack/update_bundle_catalog.sh

patch to Enterprise Contract checks.
- Closes #

OLS-567: update bundle image vendor label to 'Red Hat, Inc.'

---

lightspeed-catalog-4.15.Dockerfile
lightspeed-catalog-4.16.Dockerfile

fix FBC license

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

OLS-567 update bundle version to 0.1.0

---

lightspeed-catalog-4.15.Dockerfile
lightspeed-catalog-4.16.Dockerfile

Trigger build nin konflux to get release image.
- Closes #

[OLS] updated docker comments

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

OLS release 0.1.1

---

README.md

Added an example for configuring azure user assigned identity.
- Closes #

added example for azure openai secret

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

Add olsconfig to collector sidecar.

OLS-514: Add olsconfig to collector sidecar

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

OLS release 0.1.2 version update
- Closes #

OLS release 0.1.2 version update

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

OLS 0.1.3 version update
- Closes #

OLS 0.1.3 version update

---

hack/snapshot_to_catalog.sh

Added skipRange to snapshot_to_catalog.sh
- Closes #

Added skipRange to snapshot_to_catalog.sh

---

README.md

- should be OpenAI not OpenAPI
- should not need "-", under "type"
- Closes #

docs: fix wrong name and yaml format

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

OLS 0.1.4 version update
- Closes #

OLS 0.1.4 version update

---

.tekton/bundle-push.yaml
.tekton/lightspeed-operator-push.yaml

This is for fixing a EC violations:
- tasks.required_tasks_found:prefetch-dependencies
- tasks.required_tasks_found:source-build
- Related Issue # [OLS-889](https://issues.redhat.com//browse/OLS-889)
- Closes #

OLS-889 konflux: enable build-source and prefetch dependencies

---

bundle.Dockerfile
bundle/metadata/annotations.yaml

Ensure operator configures required OCP and Kubernetes version
- Closes # https://issues.redhat.com/browse/OLS-873

OLS-873: Ensure operator configures required OCP and Kubernetes version

---

.tekton/bundle-pull-request.yaml
.tekton/lightspeed-operator-pull-request.yaml

- Related Issue # [OLS-889](https://issues.redhat.com//browse/OLS-889)
- Closes #

OLS-889 konflux: build-source and prefetch activate for pull requests

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Turn on hermetic build on bundle and operator components.
- Related Issue # [OLS-889](https://issues.redhat.com//browse/OLS-889)
- Closes #

OLS-889 konflux: hermetic build activate on bundle and operator

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/default/kustomization.yaml

Updated bundle per snapshot ols-678gh operand images for OLS v 0.1.4
- Closes #

OLS 0.1.4 - updated bundle per snapshot ols-678gh

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

Prepare for ols release 0.1.5
- Closes #

[OLS]  prepare for ols release 0.1.5

---

.tekton/lightspeed-operator-pull-request.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

Make data collection is off when there is no pull-secret.
- Closes #

[OLS-871]  datacollection is off when there is no pull-secret

---

.tekton/test-bundle-pull-request.yaml
.tekton/test-bundle-push.yaml

Correcting cel expressions

---

testbundle.Containerfile

Adding testbundle containerfile to create new component

---

testbundle.Containerfile

Added two more sed commands to correct the service and console images

---

.tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml

Adding OLS bundle installation

---

.tekton/integration-tests/integration-test-scenarios/e2e-tests.yaml
.tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml

OLS-1021 - Adding e2e tests task and mounting secrets in it.

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog/index.yaml

update release version to 0.1.6
- Closes #

 update release version to 0.1.6

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml

Correction of description of the field ModelSpec in the OLSConfig CRD.
- Closes #

CSV: correct description of ModelSpec

---

internal/controller/ols_app_server_assets_test.go
internal/controller/ols_app_server_deployment.go

Adding perf testing suggestios: https://docs.google.com/presentation/d/1hhQjf20oW1w_DX6w9TaucTEkpIQocePB4g6uHcOOJJg/edit#slide=id.g30326bad413_0_3
- Closes # https://issues.redhat.com/browse/OLS-1086
Tested in local by deploying the application. Verified limits and probes are getting populated accordingly.

Adding perf-testing suggestion to the ols app deployment

---

.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline.yaml

OLS-1090 - Adding operator e2e tests pipeline

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog-4.17/index.yaml
lightspeed-catalog/index.yaml

OLS release 0.1.7
- Closes # https://issues.redhat.com/browse/OLS-1083

OLS release 0.1.7

---

internal/controller/ols_console_reconciliator.go

This PR allows operator retry updating the console object `cluster` when version conflict happens.
This can happen often because the console object is shared by all the cluster.
This eliminates the confusing log like 
```
2024-10-03T19:35:22+02:00	ERROR	Reconciler	Failed to remove console UI	{"error": "failed to deactivate Console Plugin: failed to update Console: Operation cannot be fulfilled on consoles.operator.openshift.io \"cluster\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/openshift/lightspeed-operator/internal/controller.(*OLSConfigReconciler).Reconcile
/home/hasun/GitRepo/lightspeed-operator/internal/controller/olsconfig_controller.go:125
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile …
```

retry on conflict: cluster console object

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
lightspeed-catalog-4.15/index.yaml
lightspeed-catalog-4.16/index.yaml
lightspeed-catalog-4.17/index.yaml

OLS release 0.2.0 component SHAs
Updated the operator SHA since it moved since the last SHA update
- Closes #

OLS release 0.2.0 component SHAs: operator

---

OWNERS

Add josh and removed Vladimir from approvers
- Closes #

add Josh and removed Vladimir from approvers

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml

Remove enterprise contract warnings from Konflux pipelines -  - bundle
- Related Issue # https://issues.redhat.com/browse/OLS-1151
- Closes #

OLS-1151: Remove enterprise contract warnings from Konflux pipelines - bundle

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Added APIVersion support for Azure Open AI.  This allows user to specify the API version that need to be used for chat completion API.
https://issues.redhat.com/browse/OLS-1092
- Related Issue #[OLS-1092](https://issues.redhat.com//browse/OLS-1092)
- Closes #

[OLS-1092] added APIVersion part of CRD

---

.tekton/test-bundle-pull-request.yaml
.tekton/test-bundle-push.yaml

Correcting cel expressions for new test bundle component in separate application

---

.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.15.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.17.yaml

of dependencies previously being called without pdm
- Closes #

OLS-1110 - Removing direct dependency installs 

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml

Add project and org to the Konflux Snyk task so Snyk scan results are sent to snyk.io.
- Related Issue # https://issues.redhat.com/browse/OLS-1271
- Closes #

OLS-1271: Added project and org to the Konflux Snyk task

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml

Adding UI pipelines
- Closes #

OLS-427 - Adding UI pipelines

---

.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml

Upgrading go version in konflux containers

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

These Konflux task migrations are done:
https://github.com/konflux-ci/build-definitions/blob/main/task/fbc-related-image-check/0.2/MIGRATION.md
https://github.com/konflux-ci/build-definitions/blob/main/task/fbc-validation/0.2/MIGRATION.md
https://github.com/konflux-ci/build-definitions/blob/main/task/inspect-image/0.2/MIGRATION.md
https://github.com/konflux-ci/build-definitions/blob/main/task/sast-snyk-check-oci-ta/0.3/MIGRATION.md
- Closes #

Konflux upgrade: deprecated tasks migration

---

go.mod
go.sum
internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go

upgrade github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring to v0.76.2
- Related Issue # 
- Closes # [OLS-1029](https://issues.redhat.com//browse/OLS-1029)

OLS-1029 dependency upgrade

---

.tekton/bundle-pull-request.yaml
.tekton/bundle-push.yaml
.tekton/lightspeed-operator-push.yaml

konflux pipeline nudges related_images.json and bundle pipeline is triggered by related_images.json
- Closes #

config: konflux pipeline updates around related_images.json

---

testbundle.Containerfile

test: sync testbundle with delivery bundle

---

.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.17.yaml

- [x ] Configuration Update
- Closes #

OLS-1291 - Adding complete e2e tests files

---

.tekton/integration-tests/pipelines/rapidast-scan.yaml
Makefile
ols-rapidast-config.yaml
test/e2e/client.go
test/e2e/rapidast_test.go

OLS application has to run RapiDast scan. Added initial config files
- Related Issue # [OLS-967](https://issues.redhat.com//browse/OLS-967) https://issues.redhat.com/browse/OLS-967
- Closes #

[OLS-967] initial config for rapidast tests

---

test/e2e/client.go

test: increase deployment condition timeout to 15m
reduce flakiness in deployment condition checks
no better conditions checks are found for checking a deployment is rolled out, we increase the timeout instead.
- Related Issue # [OLS-1333](https://issues.redhat.com//browse/OLS-1333)
- Closes #

OLS-1333 test: increase deployment condition timeout to 15m

---

.tekton/integration-tests/pipelines/rapidast-scan.yaml
test/e2e/rapidast_test.go

Updated final url for Rapidast Test config
- Closes #

Added console url to Rapidast Test config

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml
related_images.json

added related image using snapshot ols-24ktd for release 0.3.0
- Closes #

added related image using snapshot ols-24ktd

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

Reversed the arm build  for catalog for v0.3.0 release - as we don't have all operand images ready.
- Closes #

[ols ] reversed arm build for catalog

---

.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml

Removing test_user_data_collection test using tag

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml

so that OOM is not killed during the process
- [x ] Bug fix
- Closes #

Adding memory to the pod running the console tests 

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

Bump to version 0.3.1 for OLS release
- Closes #

Bump to version 0.3.1

---

related_images.json

updated release 0.3.1 with snapshot ols-lvdfg
--------
oc get snapshot ols-lvdfg -o yaml
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
name: ols-lvdfg
spec:
application: ols
artifacts: {}
components:
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-service@sha256:8c208e6e0d6b5e2b4056558fecc6f34bd0ce110075984abea2d82ef3446f0a4c
name: lightspeed-service
source:
git:
revision: 22d42926b5cbeaa27b93c12452a535f6904ef5f2
url: https://github.com/openshift/lightspeed-service
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-console@sha256:02e76210b42d3f3a716195f992466152829c8fccac3d338378e90b65fa76896e
name: lightspeed-console
source:
git:
dockerfileUrl: Dockerfile
revision: …

updated release 0.3.1 with snapshot ols-lvdfg

---

related_images.json

updated related images with snapshot ols-4hs89 for release v0.3.1
components:
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-console@sha256:dbc291c7855a9b276227fe61ea4e6e4a8d7daad872f46c221baa4685fc199627
name: lightspeed-console
source:
git:
dockerfileUrl: Dockerfile
revision: 6348b2a2ef9850bbc516ae67f0ab85c807e68a81
url: https://github.com/openshift/lightspeed-console
- containerImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-operator@sha256:e6c4d21f07b9c62442decae7189245a3bcf72505ea638b47bf15ff7f6d62a111
name: lightspeed-operator
source:
git:
dockerfileUrl: Dockerfile
revision: 8e6aeb65f792de4d946fea0b705d527a882918a1
url: https://github.com/openshift/lightspeed-operator
- containerImage: …

updated related images with snapshot ols-4hs89

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

Added fbc-fips-check-oci-ta check to resove EC violation.
- Closes #

fbc-fips-check-oci-ta check added

---

.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml

OLS-1489 - Changing run calling to script.

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml

Dummy commit to trigger the pipeline
- Closes #

 Dummy commit to trigger the pipeline

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

Added fips check for bundle
- Related Issue #https://issues.redhat.com/browse/OLS-1444
- Closes #

added fips check for bundle

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

Bump to version 0.3.2

---

related_images.json

add snapshot ols-bsdq2 for bundle for release 0.3.2
- Closes #

add snapshot ols-bsdq2 for bundle

---

.tekton/fbc-v4-18-pull-request.yaml
.tekton/fbc-v4-18-push.yaml

updated FBC  4.18 pipeline with fips task.
- Closes #

updated  FBC 4.18 pipeline with fips task

---

related_images.json

fixed service image version
- Closes #

fixed service image version

---

.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml

, list those and test artifacts and upload everything to quay
quay.io/openshift-lightspeed/ols-service-artifacts
the sha for the bundle PR will match the sha for the artifacts.
- Closes #

OLS-1471 - Adding tasks to export konflux artifacts

---

Makefile
bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

prepare for release 0.3.3
- Closes #

Bump to version 0.3.3

---

related_images.json

update related_images.json for release 0.3.3
snapshot is [ols-rj8gs ](https://console.redhat.com/application-pipeline/workspaces/crt-nshift-lightspeed/applications/ols/snapshots/ols-rj8gs)
- Closes #

update related_images.json for release 0.3.3

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml
.tekton/fbc-v4-18-pull-request.yaml
.tekton/fbc-v4-18-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml
.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

[](config: add to konflux pipeline: sast-shell-check-oci-ta, sast-unicode-check-oci-ta)
- Closes #

config: EC check fix, add 2 new tasks

---

.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml

in the same task. Avoid false positives caused by onError: continue
Also synced 4.15 and 4.16 pipelines with 4.17.
- Closes #

Adding step to fail when a step has failed previously

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/olsconfig_controller.go

fix: PostgreSQL settings have display name and descriptions generated in CSV + kubebuilder tag for permission

---

.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.15.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml
.tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.17.yaml

[OLS-1619](https://issues.redhat.com//browse/OLS-1619): konflux: Split e2e test pipelines for service and operator.

OLS-1619: konflux: Split e2e pipelines for service and operator

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/olsconfig_controller.go

restricted rbac for secret and clusterrole/bindings
- Related Issue [#](https://issues.redhat.com/browse/OLS-1495)
- Closes [#](https://issues.redhat.com/browse/OLS-1495)

restricted rbac for secret and clusterrole/bindings

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

Prepare release 0.3.4
- Related Issue # [OLS-1643](https://issues.redhat.com//browse/OLS-1643)
- Closes #

OLS-1643: Bump to version 0.3.4

---

hack/version_patches/konflux-release-data.patch
hack/version_patches/service.patch

Update the version patches on konflux-release-data and lightspeed-service.
- Closes #

tool: fix version patches

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml

Fixing console tests and syncing with console pre-commit version

---

internal/controller/ols_console_ui_assets.go
internal/controller/ols_console_ui_assets_test.go

updated console label for networkpolicy 
- Closes #

updated console label for networkpolicy 

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml

instead of console image in bundle tests
- Closes #

NO_JIRA: Fixing console tests to install using bundle image 

---

related_images.json

related image only. 
check the konflux E2E tests
- Closes #

conf: update related images for bundle 0.3.4

---

bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
lightspeed-catalog-4.17/index.yaml
lightspeed-catalog-4.18/index.yaml

Corrected docs links on the operator installation tile to point to docs.redhat.com
- Closes #

Corrected docs links on the operator installation tile

---

.tekton/lightspeed-operator-push.yaml

conf: operator does not nudge catalog.

---

.gitignore
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
test/e2e/autocorrection_test.go
test/e2e/constants.go
test/e2e/metrics_test.go
test/e2e/rapidast_test.go
test/e2e/reconciliation_test.go
test/e2e/suite_test.go
test/e2e/tls_test.go
test/e2e/utils.go

OLS-1733 - Adding artifact exporting

---

related_images.json

release candidate snapshot ols-k95wt
check E2E tests in this PR before merge.
- Closes #

conf: update related-images with snapshot ols-k95wt

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml

OLS-1710: Add artifact gathering and exporting to console tests

---

.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml

- Related Issue # [OLS-1734](https://issues.redhat.com//browse/OLS-1734)
- Closes #

OLS-1734: conf: trigger bundle rebuild for release 0.3.5 with konflux pipeline fixes

---

internal/controller/ols_app_postgres_assets.go
internal/controller/ols_app_postgres_assets_test.go

Add postgre container memory limit
- Closes #

OLS-1741: Add postgre container memory limit

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml
.tekton/fbc-v4-18-pull-request.yaml
.tekton/fbc-v4-18-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml
.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

conf: update konflux build-image-index to resolve EC issue

---

related_images.json

this snapshot has a fix on MCP server issue.
snapshot date May 28, 2025, 3:47 PM UTC
- Related Issue # [OLS-1734](https://issues.redhat.com//browse/OLS-1734)
- Closes #

OLS-1734: update related images with snapshot ols-pwv4j for release 0.3.5

---

related_images.json

GA -Release : updated related_images with GA operand images
- Closes #

updated with GA operand images

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml

bump bundle version to 1.0.0

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml

Fixing false positives in UI tests

---

internal/controller/ols_app_server_deployment.go

lint: remove useless nil check

---

.tekton/fbc-v4-19-pull-request.yaml
.tekton/fbc-v4-19-push.yaml
bundle.Dockerfile
hack/release-konflux/kustomization.yaml
hack/template_bundle.Containerfile
lightspeed-catalog-4.19.Dockerfile
lightspeed-catalog-4.19/index.yaml
renovate.json

Added support for the FBC catalog for OCP 4.19
- Closes # https://issues.redhat.com/browse/OLS-1514

OLS-1514: Configure FBC catalog release for OCP 4.19

---

.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/fbc-v4-16-pull-request.yaml
.tekton/fbc-v4-16-push.yaml
.tekton/fbc-v4-17-pull-request.yaml
.tekton/fbc-v4-17-push.yaml
.tekton/fbc-v4-18-pull-request.yaml
.tekton/fbc-v4-18-push.yaml
.tekton/lightspeed-operator-pull-request.yaml
.tekton/lightspeed-operator-push.yaml
.tekton/ols-bundle-pull-request.yaml
.tekton/ols-bundle-push.yaml

This PR replaces https://github.com/openshift/lightspeed-operator/pull/768
- Closes #

Konflux task upgrade + apply-tags migration

---

api/v1alpha1/olsconfig_types.go
bundle/manifests/ols.openshift.io_olsconfigs.yaml
config/crd/bases/ols.openshift.io_olsconfigs.yaml

- Closes # [OLS-1804](https://issues.redhat.com//browse/OLS-1804)

OLS-1804 bugfix: ols.defaultProvider should be required in UI

---

hack/bundle_to_catalog.sh

add a tool script that generate catalog from bundle snapshot and the existing `related_images.json`.
part of release automation in konflux.

tool: add bundle_to_catalog.sh

---

.tekton/release/bundle-update/pipeline.yaml
.tekton/release/catalog-update/pipeline.yaml

konflux: bugfix on bundle-update pipeline

---

hack/snapshot_to_catalog.sh

tool: bugfix on snapshot_to_catalog.sh

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
hack/update_bundle_catalog.sh

Bump to 1.0.2

---

.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-418.yaml

Stopping snapshot exporting from failing tests

---

hack/release-konflux/kustomization.yaml

Kustomization for the latest release
- Closes #

Kustomization for the latest release

---

internal/controller/ols_app_server_assets.go
internal/controller/ols_app_server_assets_test.go
internal/controller/types.go

Moved the api_version to ProviderConfig to match the OLS Service Config - to resolve the problem reported below.
(https://access.redhat.com/support/cases/#/case/04195716)
- [ x] Bug fix
- Closes #

moved api_version to ProviderConfig to match the Service Config

---

related_images.json

This PR is triggered by the release crt-nshift-lightspeed-tenant/stable-ols-1.0.3-1.

Bundle Update from Snapshot crt-nshift-lightspeed-tenant/ols-tfwxx

---

hack/version_patches/konflux-release-data.patch

OLS-1954: fix: update the version patch of konflux-release-data

---

.tekton/integration-tests/pipelines/lightspeed-operator-upgrade-e2e-test-pipeline-418.yaml
Makefile
test/e2e/client.go
test/e2e/upgrade_test.go

OLS-1746 - Creating upgrade test for OLS operator

---

go.mod

updated go toolchain to 1.23.10
- Closes [OLS-1930](https://issues.redhat.com/browse/OLS-1930)
- [OLS-1931](https://issues.redhat.com/browse/OLS-1931)
- [OLS-1932](https://issues.redhat.com/browse/OLS-1932)

 [OLS-1930] updated go toolchain to 1.23.10

---

.tekton/integration-tests/pipelines/lightspeed-operator-upgrade-e2e-test-pipeline-416.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-upgrade-e2e-test-pipeline-417.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-upgrade-e2e-test-pipeline-418.yaml
.tekton/integration-tests/pipelines/lightspeed-operator-upgrade-e2e-test-pipeline-419.yaml

Fixing yq installation

---

test/e2e/proxy_test.go

Removing PVC deletion from cleanup

---

docs/olsconfig-ols-openshift-io-v1alpha1.adoc

API docs update for the MCP servers feature
- Closes #

API docs update for the MCP servers feature

---

related_images.json

This PR is triggered by the release crt-nshift-lightspeed-tenant/stable-ols-1.0.5-2.

Bundle Update from Snapshot crt-nshift-lightspeed-tenant/ols-nwkcm

---

Makefile

Use a conditional assignment (?=) instead, which only sets the variable if it's not already defined. 
Also fixes the comment to reflect the logic.
- Closes #

Conditional assignment of CONTAINER_TOOL

---

.tekton/release/catalog-update/pipeline.yaml
bundle.Dockerfile
lightspeed-catalog-4.20.Dockerfile
lightspeed-catalog-4.20/index.yaml

added 4.20 config for FBC catalog 
- [X ] New feature
- Related Issue [#](https://issues.redhat.com/browse/OLS-2096)
- Closes #

 added 4.20 config for FBC catalog

---

bundle.Dockerfile
bundle/manifests/lightspeed-operator.clusterserviceversion.yaml

Bump to version 1.0.6
- Related Issue # [OLS-2137](https://issues.redhat.com//browse/OLS-2137)
- Closes #

OLS-2137: Bump to version 1.0.6

---

lightspeed-catalog-4.20.Dockerfile

updated the base image for FBC 4.20
- Closes #

 updated the base image for FBC 4.20

---

.tekton/fbc-v4-20-pull-request.yaml
.tekton/fbc-v4-20-push.yaml

post fbc 4.20 pipeline creation
setup trigger condition + activate hermetic + activate build source image
- Related Issue # [OLS-2096](https://issues.redhat.com//browse/OLS-2096)
- Closes #

OLS-2096 conf: fbc 4.20 pipeline trigger condition + hermetic + build source image

---

.tekton/fbc-v4-20-pull-request.yaml
.tekton/fbc-v4-20-push.yaml

conf: konflux fbc-v4-20 - trigger condition

---

related_images.json

This PR is triggered by the release crt-nshift-lightspeed-tenant/stable-ols-1.0.6-3.

Bundle Update from Snapshot crt-nshift-lightspeed-tenant/ols-hcb4z

---

.tekton/release/catalog-update/pipeline.yaml

tool: include fbc 4.20 in automatic catalog update pipeline
